baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "SchoolNew: ОБучение фотографии"
# theme = "blowfish"
# theme = "wowchemy"
enableRobotsTXT = true

[params]
  description = "Индивидуальное обучение фотографии"

  [params.author]
     name = "Юрий Гуревич"
      email = "biggur@mail.ru"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Главная"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "courses"
    name = "Курсы"
    url = "/courses/"
    weight = 2

  [[menu.main]]
    identifier = "masters"
    name = "Мастера фотографии"
    url = "/masters/"
    weight = 3

[pagination]
  pagerSize = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true